### ISSUE TITLE
Describe use of analytics in README

### ISSUE THREAD

**Issue by ross-spencer** [simonw/datasette-lite#61]
It'd be great to get a statement about how the analytics in this tool are used. I.e. what's collected, and how it's used. Possibly something for the README. Further, perhaps it can be made easier to toggle on and off? 

https://github.com/simonw/datasette-lite/blob/e402b4e60dcfbf668980cc1425cbfde1c29d8514/index.html#L172-L173

Connected to: https://github.com/simonw/datasette-lite/issues/22
Partially connected to: https://github.com/pyodide/pyodide/issues/140#issuecomment-1406516885

**Comment by simonw** [comment]
This is a good call. I'll document the analytics and add a `?analytics=off` parameter that can be used to opt out entirely - useful for people who want to link to Datasette Lite but don't want the URL they are opening to be logged anywhere (outside of any GitHub Pages logs which I have no control over or visibility into).

**Comment by simonw** [comment]
With `?analytics=off`:

<img width="1286" alt="CleanShot 2023-03-16 at 16 36 09@2x" src="https://user-images.githubusercontent.com/9599/225775438-bbf46e43-bf7c-4160-9631-5f2c9afdec9e.png">

There's one fetch to Plausible to get the `script.manual.js` file but there are no further hits actually tracking analytics.

Without that parameter:

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/9599/225775525-1dd04022-de38-4c28-a469-cd8a6de3aacd.png">

Note two hits to `event` on Plausible, because I navigated within the interface after it loaded.

**Comment by simonw** [comment]
Here's the new section in the README: https://github.com/simonw/datasette-lite/blob/main/README.md#analytics
